name: Deploy to Google Cloud Build

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to GCP
      run: |-
        echo '${{ secrets.GCLOUD_AUTH }}' > gcloud_auth_key.json
        gcloud auth activate-service-account --key-file=gcloud_auth_key.json
        gcloud config set project stockmarketindexai
        gcloud builds submit --config docker/cloudbuild.yaml
      env:
        GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
