name: Deploy to Google Cloud Run

on:
    push:
      branches:
        - main

jobs:
    build_and_deploy:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Setup Google Cloud CLI
          run: |-
            echo '${{ secrets.GCLOUD_AUTH }}' > gcloud_auth_key.json
            gcloud auth activate-service-account --key-file=gcloud_auth_key.json
            gcloud config set project stockmarketindexai
          env:
            GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
    
        # - name: Build and Push to Google Container Registry
        #   run: |-
        #     gcloud builds submit --config docker/cloudbuild.yaml

        - name: Authenticate to Google Cloud
          uses: google-github-actions/auth@v0.4.0
          with:
            credentials_json: ${{ secrets.GCLOUD_AUTH }}

        - name: Deploy to Cloud Run
          uses: google-github-actions/deploy-cloudrun@main
          with:
            service: stockmarketindexai
            image: gcr.io/stockmarketindexai/linebot-lstm@sha256:077035e6f5e5eab7f31e836b79dddbc62cd783681d9676ed14867127a6d6647b
            region: asia-east1
